services:
  ai-tools:
    build: .
    container_name: ai-tools
    env_file:
      - .env
    ports:
      - "8010:8000"
    networks:
      - ai_stack
    shm_size: "1gb"
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: ai-tools-postgres
    environment:
      POSTGRES_DB: aitools
      POSTGRES_USER: aitools
      POSTGRES_PASSWORD: Nbkbvbkbnhzv1!
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ai_stack
    restart: unless-stopped
    ports:
      - "5432:5432"

volumes:
  postgres_data:

networks:
  ai_stack:
    external: true